### PR TITLE
update to opensuse 13.2

### PR DESCRIPTION
**Pull request by gimler**
because mirror doesn't exist anymore

### CODE REVIEW

**Comment by flavio** [comment]
@schaefi can you take a look at this PR, the image is used just by your `dice` tool AFAIK.

I think it would be nice to upgrade to 42.2 and also to set you ( @schaefi ) as `MAINTAINER` of it.

**Comment by schaefi** [comment]
Hmm, no I think that is not one of mine. For dice I'm using this image:
- https://hub.docker.com/r/opensuse/dice

The corresponding buildservice project building the image which then gets uploaded to dockerhub is here:
- https://build.opensuse.org/package/show/Virtualization:Appliances:Images/dice-image-docker

This is also already based on Tumbleweed

So I'm sorry the image I use is not based on the mentioned Dockerfile

**Comment by schaefi** [comment]
I guess derived_images/kiwi is an orphaned space in this git repo, at least I do not use it

**Comment by flavio** [comment]
Closing the PR, I just removed this image.

**Pull request closed without merging**
