### PR TITLE
Fix Leap 42.3 repos, fixes #64

### LINKED ISSUE #64: Wrong repository found in Leap 42.3 docker image
There is no repository at [http://download.opensuse.org/update/42.3](http://download.opensuse.org/update/42.3)

```bash
bash-4.3# zypper lr -U
Repository priorities are without effect. All enabled repositories share the same priority.

# | Alias          | Name           | Enabled | GPG Check | Refresh | URI                                                              
--+----------------+----------------+---------+-----------+---------+------------------------------------------------------------------
1 | non-oss        | NON-OSS        | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/distribution/leap/42.3/repo/non-oss/
2 | oss            | OSS            | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/distribution/leap/42.3/repo/oss/    
3 | oss-update     | OSS Update     | Yes     | ( p) Yes  | Yes     | http://download.opensuse.org/update/42.3/                        
4 | update-non-oss | Update Non-Oss | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/42.3/non-oss/           
bash-4.3# zypper ref
Repository 'NON-OSS' is up to date.                                                                                                    
Repository 'OSS' is up to date.                                                                                                        
Retrieving repository 'OSS Update' metadata ----------------------------------------------------------------------------------------[\]
File '/repodata/repomd.xml' not found on medium 'http://download.opensuse.org/update/42.3/'

Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
Retrieving repository 'OSS Update' metadata ....................................................................................[error]
Repository 'OSS Update' is invalid.
[oss-update|http://download.opensuse.org/update/42.3/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'OSS Update' because of the above error.
Repository 'Update Non-Oss' is up to date.                                                                                             
Some of the repositories have not been refreshed because of an error.
```

How to fix it:

```bash
bash-4.3# zypper rr 3
Removing repository 'OSS Update' ................................................................................................[done]
Repository 'OSS Update' has been removed.
bash-4.3# zypper ar -f http://download.opensuse.org/update/leap/42.3/oss/openSUSE:Leap:42.3:Update.repo
Adding repository 'Online updates for openSUSE Leap:42.3 (standard)' ............................................................[done]
Repository 'Online updates for openSUSE Leap:42.3 (standard)' successfully added

URI         : http://download.opensuse.org/update/leap/42.3/oss/
Enabled     : Yes                                               
GPG Check   : Yes                                               
Autorefresh : Yes                                               
Priority    : 99 (default priority)                             

Repository priorities are without effect. All enabled repositories share the same priority.
bash-4.3# zypper ref
Repository 'NON-OSS' is up to date.                                                                                                    
Retrieving repository 'Online updates for openSUSE Leap:42.3 (standard)' metadata ...............................................[done]
Building repository 'Online updates for openSUSE Leap:42.3 (standard)' cache ....................................................[done]
Repository 'OSS' is up to date.                                                                                                        
Repository 'Update Non-Oss' is up to date.                                                                                             
All repositories have been refreshed.
```

### PR DESCRIPTION
**Pull request by davidcassany**
This PR fixes the 'OSS Update' repository URI

### CODE REVIEW

**Comment by davidcassany** [comment]
@drpaneas I have tested it [here](https://build.opensuse.org/project/show/home:dcassany:branches:openSUSE:Leap:42.3), could you confirm it works fine? Then I'll proceed with the merge. 

Thanks

**Comment by drpaneas** [comment]
Hi @davidcassany 

I tested it just now taking the images taken from your personal OBS branch/project, but the problem this time is that there are no repositories at all. For example:

```bash
Warning: No repositories defined. Operating only with the installed resolvables. Nothing can be installed.
Warning: No repositories defined.
Use the 'zypper addrepo' command to add one or more repositories.
```

**Comment by davidcassany** [comment]
@drpaneas you are completely right, my fault, I did not point you to the correct project of my personal OBS branch (I really need to clean my personal home...), this is the repository containing the changes of this PR: 
https://build.opensuse.org/package/show/home:dcassany:branches:Virtualization:containers:images:openSUSE-42.3/openSUSE-42.3-docker-image

Sorry for the noise and wasting part of your time.

**Comment by drpaneas** [comment]
No problem at all David :)

Now that you pointed me with the correct project, my *new* problem is that I cannot download the images. I've looked into it, but all the directories and subdirectories seem to be [empty](http://download.opensuse.org/repositories/home:/dcassany:/branches:/Virtualization:/containers:/images:/).

I also went [through](https://build.opensuse.org/package/binaries/home:dcassany:branches:Virtualization:containers:images:openSUSE-42.3/openSUSE-42.3-docker-image?repository=images) but clicking at the  [Go to download repository](http://download.opensuse.org/repositories/home:/dcassany:/branches:/Virtualization:/containers:/images:/openSUSE-42.3/images) gives me a **404**.

I've tried to *checkout* the project locally, but I am afraid I do not know how to trigger the build for the images with KIWI. Here's what I've tried so far:

```bash
$ obs co home:dcassany:branches:Virtualization:containers:images:openSUSE-42.3
A    home:dcassany:branches:Virtualization:containers:images:openSUSE-42.3
A    home:dcassany:branches:Virtualization:containers:images:openSUSE-42.3/openSUSE-42.3-docker-image
A    home:dcassany:branches:Virtualization:containers:images:openSUSE-42.3/openSUSE-42.3-docker-image/_service
```

```bash
$ cd home\:dcassany\:branches\:Virtualization\:containers\:images\:openSUSE-42.3/
$ cd openSUSE-42.3-docker-image/
$ ibs service localrun
Cloning into '/home/panos/leap/home:dcassany:branches:Virtualization:containers:images:openSUSE-42.3/openSUSE-42.3-docker-image/docker-containers'...
From https://github.com/openSUSE/docker-containers
 * [new branch]      fix_leap_42.3_repos -> fix_leap_42.3_repos
ce0c7f8c25f689f04e0816ba5f0e5fccb76da0f9
Extracting from /home/panos/leap/home:dcassany:branches:Virtualization:containers:images:openSUSE-42.3/openSUSE-42.3-docker-image/openSUSE-42.3-docker-image-1497538915.ce0c7f8.tar:
   */config.kiwi */config.sh */root.tar.bz2
```

^ what's the next step?

**Comment by davidcassany** [comment]
Hi to build locally it is done by running the following from the package folder:
```bash
$ osc service run
$ osc build images
```

Also the image should be downloadable without having to access the repository, I think that navigating throught the OBS web frontend to the binary information it can be downloaded. Anyway I have just enabled the repository so now you should be capable of downloading it.

Thanks!

**Comment by drpaneas** [comment]
Thanks for the information :)

```bash
bash-4.3# zypper lr -U
Repository priorities are without effect. All enabled repositories share the same priority.

# | Alias          | Name           | Enabled | GPG Check | Refresh | URI                                                              
--+----------------+----------------+---------+-----------+---------+------------------------------------------------------------------
1 | non-oss        | NON-OSS        | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/distribution/leap/42.3/repo/non-oss/
2 | oss            | OSS            | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/distribution/leap/42.3/repo/oss/    
4 | update-non-oss | Update Non-Oss | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/42.3/non-oss/           
3 | oss-update     | OSS Update     | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/42.3/oss/ 
```

/LGTM from my side 👍

**Comment by davidcassany** [comment]
Great thanks, I am merging then 👍

**Comment by davidcassany** [comment]
@drpaneas, now in some minutes the build should be also updated in Virtualization:containers:images:openSUSE-42.3 OBS project

**Pull request merged**
