### PR TITLE
set excludedocs to zypper configuration

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
so that the image does not get the docs when running zypper update.

### CODE REVIEW

**Comment by flavio** [comment]
That looks good, however I just realized we ship tumbleweed's root FS uncompressed. That does not work on OBS. Can you create a root.tar.bz2 also for tumbleweed?

**Comment by jordimassaguerpla** [comment]
sure

**Comment by jordimassaguerpla** [comment]
should I update the version number in the kiwi file?

**Comment by flavio** [comment]
Yes please, can you also take care of propagating the changes to the Docker
hub?

**Pull request merged**
