### PR TITLE
Add Dockerfile for opensuse-based kubectl

### PR DESCRIPTION
**Pull request by HartS**

### CODE REVIEW

**Comment by flavio** [comment]
This image should be changed to use packages built by the build service for openSUSE. Adding static binaries build by third parties is not considered a best practice.

The right approach would be to get `kubectl` by installing the package that provides it (`kubernetes-client` from `obs://Virtualization:containers` - the package is going to land into the main repos of 42.3 because it's already on Factory).

Please take a look at [this image](https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus) to see how the external repository can be added in a secure way.

**Comment by HartS** [comment]
Thanks for the feedback. I updated my branch with a commit which uses OBS now.

**Comment by cornelius** [comment]
@flavio Out of curiosity: Why is the key fetched from the key server at build time instead of putting it into the sources of the docker build?

**Comment by flavio** [comment]
> @flavio Out of curiosity: Why is the key fetched from the key server at build time instead of putting it into the sources of the docker build?

We had a discussion with upstream about the best way to add repositories gpg keys into generic hosts (could be containers or traditional systems). This was the solution we agreed upon because it was considered the most secure one.

**Pull request merged**
