### PR TITLE
Fix openSUSE Leap images names

### PR DESCRIPTION
**Pull request by davidcassany**
This commits makes a correction on the openSUSE image naming criteria.
"Leap" is part of the official name, thus the complete name for the
openSUSE images must include it, for instance, "openSUSE Leap 42.3"
instead of "openSUSE 42.3".

### CODE REVIEW

**Comment by davidcassany** [comment]
@flavio, @jordimassaguerpla, this is a kind of a nit-picking PR, but anyway Ludwig Nussel noted me in a mail that if at some point we are likely to publish any kind of openSUSE kiwi Docker template we should use official openSUSE names.

**Comment by davidcassany** [comment]
@jordimassaguerpla, @monstermunchkin is there anything else automated from that repo apart from the service in OBS? If approved this PR will change the name of the image tarball and I am wondering would could be broken by this change.

**Comment by jordimassaguerpla** [comment]
We will have to change our ci that imports this to docker hub, in the namespace opensuse/amd64.

**Comment by jordimassaguerpla** [comment]
Also the tarball and dockerfile in
https://github.com/openSUSE/docker-containers-build/tree/openSUSE-42.2/docker

**Comment by jordimassaguerpla** [comment]
And as you said, in the openbuildservice.

**Comment by flavio** [comment]
I'm fine doing this change, however make sure you also fix all the quirks this is going to introduce (see what @jordimassaguerpla said above).

**Comment by davidcassany** [comment]
I am closing that PR, since we have also to update images to make use of the current native docker image in kiwi-ng and it will have also impact on the CI and on the docker-containers-build repository, thus it will be also the right time to make the name updated suggested in this PR.

**Pull request closed without merging**
