### PR TITLE
Proposal to change your setup for direct using of root layer files

### PR DESCRIPTION
**Pull request by adrianschroeter**
You can maintain your files directly in git without the need to submit a tar ball.

Just adapted it for 42.3, but it should be easy to adapt the rest for you.

You need to adapt your service file like here in OBS:

home:adrianSuSE:branches:Virtualization:containers:images:openSUSE-42.3/openSUSE-42.3-docker-image

```
<services>
    <service name="obs_scm">
        <param name="url">https://github.com/adrianschroeter/docker-containers.git</param>
        <param name="scm">git</param>
        <param name="subdir">openSUSE-Leap-42.3/config</param>
        <param name="extract">config.kiwi</param>
        <param name="extract">config.sh</param>
    </service>
    <service name="obs_scm">
        <param name="url">https://github.com/adrianschroeter/docker-containers.git</param>
        <param name="scm">git</param>
        <param name="filename">root</param>
        <param name="version">_none_</param>
        <param name="subdir">openSUSE-Leap-42.3/root</param>
    </service>
</services>

```

### CODE REVIEW

**Comment by davidcassany** [comment]
@flavio, @adrianschroeter, thanks much for the update, I will give it a try, looks nice.

Meanwhile there is also this openSUSE/obs-service-tar_scm#191 I did some days ago to update the service and allow us to create the compressed root.tar.gz using the **obs_scm** and **tar** services.

**Comment by davidcassany** [comment]
@adrianschroeter, @flavio I have just explored the suggestion and I have just a couple of minor issues about it. The one I am concerned about is that you needed to restructure files in a different structure of what KIWI expects or uses, IMHO, this is kind of a non obvious workaround and I'd like to avoid it. Specially having in mind that the ideal situation would be to be capable to run the same kiwi project (or with minimal changes) locally using kiwi or remotely/locally using the build service.

The other minor issue I found is that I could not use this services locally with osc (v0.160.0). But I guess this is just an issue in OSC code that could be fixed.

**Comment by adrianschroeter** [comment]
@davidcassany where do you see the difference of the structure as kiwi needs it?

A directory containing a appliance.kiwi and a root/ directory should also work for plain kiwi, no?

**Comment by davidcassany** [comment]
@adrianschroeter in your repo I see this srtucture:

```
$ ls -R
.:
config  root

./config:
config.kiwi  config.sh

./root:
etc

./root/etc:
resolv.conf  zypp

./root/etc/zypp:
repos.d  zypp.conf
```

KIWI expects to have `config.kiwi` description file and `root` folder inside the same folder. And the same for `config.sh` and other archives like hooks or tarballs listed in the `<packages>` section. I saw you fixed that issue with _none_ as the version parameter, I will make further tests. Ideally in github we would like to have the code with the same structure as we do for this [repository](https://github.com/SUSE/kiwi-descriptions/tree/master/suse/x86_64/suse-leap-42.3-JeOS).

**Comment by adrianschroeter** [comment]
right, I have updated my git repo and also the _service file.

this should give you a layout which also works with plain kiwi. The only bogus thing is that the _service:obs_scm:docker-containers-*.obscpio file exists, but is actually not needed.
However, can be solved more elegant later and should not block you.

**Comment by davidcassany** [comment]
@adrianschroeter right, this looks nice, thanks!

**Comment by davidcassany** [comment]
@adrianschroeter looks good this proposal, I have done some tests locally, remotely, with and without disabled mode and it works fine, thanks much. Do you mind if I close this PR and I make a new one? This way I will make a single PR to uncompress all root.tar.gz tarballs.

**Comment by adrianschroeter** [comment]
sure, just go for it.

**Comment by davidcassany** [comment]
Closed as new PR is here https://github.com/openSUSE/docker-containers/pull/75

**Pull request closed without merging**
